name: research_ai
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - pip
  - pip:
    - crewai
    - crewai_tools
    - requests
    - "fastapi[standard]"
    - uvicorn
    - python-dotenv
    - PyPDF2